version: '3'

services: 
    app-golang:
        build: 
            context: ./
        container_name: app-golang
        volumes: 
            .:/go/src
volumes:
    app-golang:
        name: "app-golang"
        external: false        